Server:
  Host: "0.0.0.0"
  Port: "12062"

Postgres:
  host: "80.93.190.50"
  port: "5432"
  user: "user"
  password: "11092003"
  DBName: "mostrans"
  sslMode: "disable"
  pgDriver: "pgx"

AIClient:
  brig_ai: "80.93.190.50:5000"
  vandor_eu_ai: ""
  vendor_ru_ai: ""